name: My_CI
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
 push-to-dockerhub: 
     runs-on: self-hosted
     steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: "echo Hello, World"
        - name: Login to my Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build docker image
          run: docker build . -t ${{secrets.DOCKER_USERNAME}}/task1:latest
        - name: Push docker image to Docker hub
          run: docker push ${{secrets.DOCKER_USERNAME}}/task1:latest
 push-to-ecr:
    runs-on: self-hosted
    name: Build and Push Docker Image to ECR

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-west-2  # Replace <your-aws-region> with your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region us-west-2 docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}
        env:
          AWS_REGISTRY_URL: ${{ secrets.AWS_REGISTRY_URL }}

      - name: Build Docker image
        run: 
          docker build -t ${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }} .
          docker tag ${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }} ${{ secrets.AWS_REGISTRY_URL }}:latest

      - name: Push Docker image to ECR
        run: 
          docker push ${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }}
          docker push ${{ secrets.AWS_REGISTRY_URL }}:latest
