name: My_CI
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
 push-to-dockerhub: 
     runs-on: self-hosted
     steps: 
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: "echo Hello, World"
        - name: Login to my Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build docker image
          run: docker build . -t ${{secrets.DOCKER_USERNAME}}/task1:latest
        - name: Push docker image to Docker hub
          run: docker push ${{secrets.DOCKER_USERNAME}}/task1:latest
 push-to-ecr:
    runs-on: self-hosted
    name: Build and Push Docker Image to ECR

    steps:  
        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
            aws-region: ${{secrets.AWS_REGION}}


        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: public.ecr.aws/y8h2p9f1
            ECR_REPOSITORY: github_actions_priya
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       
