name: Build and Push NGINX Docker Image

on:
  push:
    branches:
      - main

jobs:
  build: 
     runs-on: ubuntu_latest
     steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: "echo Hello, World"
        - name: Login to my Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_IMAGE_USERNAME }}
            password: ${{ secrets.DOCKER_IMAGE_SECRETTOKEN }}
        - name: Build docker image
          run: docker build . -t ${{secrets.DOCKER_IMAGE_USERNAME}}/task1:latest
        - name: Push docker image to Docker hub
          run: docker push ${{secrets.DOCKER_IMAGE_USERNAME}}/task1:latest
